package server

import "net/http"

func (server *Server) routes() {
	server.mux.HandleFunc("POST /api/v1/auth/login", server.login)
	server.mux.HandleFunc("POST /api/v1/auth/logout", server.logout)
	server.mux.HandleFunc("GET /api/v1/auth/me", server.me)
	server.mux.HandleFunc("PUT /api/v1/auth/password", server.changePassword)
	server.mux.HandleFunc("GET /api/v1/health", server.health)
	server.mux.HandleFunc("GET /api/v1/bootstrap", server.bootstrap)
	server.mux.HandleFunc("PUT /api/v1/runtime/settings", server.saveRuntimeSettings)
	server.mux.HandleFunc("GET /api/v1/channels/weixin", server.getWeixin)
	server.mux.HandleFunc("PUT /api/v1/channels/weixin", server.saveWeixinSettings)
	server.mux.HandleFunc("POST /api/v1/channels/weixin/login", server.startWeixinLogin)
	server.mux.HandleFunc("GET /api/v1/channels/weixin/login/{id}", server.getWeixinLogin)
	server.mux.HandleFunc("DELETE /api/v1/channels/weixin/login/{id}", server.cancelWeixinLogin)
	server.mux.HandleFunc("POST /api/v1/channels/weixin/login/{id}/verify", server.verifyWeixinLogin)
	server.mux.HandleFunc("PUT /api/v1/channels/weixin/accounts/{id}", server.updateWeixinAccount)
	server.mux.HandleFunc("POST /api/v1/channels/weixin/accounts/{id}/retry", server.retryWeixinDelivery)
	server.mux.HandleFunc("DELETE /api/v1/channels/weixin/accounts/{id}", server.deleteWeixinAccount)
	server.mux.HandleFunc("GET /api/v1/usage", server.usage)
	server.mux.HandleFunc("POST /api/v1/projects", server.createProject)
	server.mux.HandleFunc("PUT /api/v1/projects/{id}", server.updateProject)
	server.mux.HandleFunc("DELETE /api/v1/projects/{id}", server.deleteProject)
	server.mux.HandleFunc("GET /api/v1/sessions/history", server.getOlderSessions)
	server.mux.HandleFunc("GET /api/v1/sessions/{id}", server.getSession)
	server.mux.HandleFunc("PATCH /api/v1/sessions/{id}", server.updateSession)
	server.mux.HandleFunc("GET /api/v1/sessions/{id}/history", server.getSessionHistory)
	server.mux.HandleFunc("GET /api/v1/attachments/{id}", server.getAttachment)
	server.mux.HandleFunc("POST /api/v1/sessions", server.createSession)
	server.mux.HandleFunc("POST /api/v1/sessions/{id}/messages", server.continueSession)
	server.mux.HandleFunc("POST /api/v1/sessions/{id}/pause", server.pauseSession)
	server.mux.HandleFunc("POST /api/v1/sessions/{id}/resume", server.resumeSession)
	server.mux.HandleFunc("POST /api/v1/sessions/{id}/cancel", server.cancelSession)
	server.mux.HandleFunc("GET /api/v1/sessions/{id}/stream", server.streamSession)
	server.mux.HandleFunc("POST /api/v1/sessions/{id}/fork", server.forkSession)
	server.mux.HandleFunc("DELETE /api/v1/sessions/{id}/worktree", server.cleanupWorktree)
	server.mux.HandleFunc("POST /api/v1/sessions/{id}/codex-request", server.resolveCodexRequest)
	server.mux.HandleFunc("DELETE /api/v1/sessions/{id}", server.deleteSession)
	server.mux.HandleFunc("PUT /api/v1/model", server.saveModel)
	server.mux.HandleFunc("PUT /api/v1/model/{id}/active", server.activateModelProfile)
	server.mux.HandleFunc("DELETE /api/v1/model/{id}", server.deleteModelProfile)
	server.mux.HandleFunc("POST /api/v1/model/test", server.testModel)
	server.mux.HandleFunc("GET /api/v1/ollama", server.getOllama)
	server.mux.HandleFunc("GET /api/v1/codex", server.getCodex)
	server.mux.HandleFunc("GET /api/v1/codex/models", server.getCodexModels)
	server.mux.HandleFunc("GET /api/v1/codex/account", server.getCodexAccount)
	server.mux.HandleFunc("GET /api/v1/codex/threads", server.getCodexThreads)
	server.mux.HandleFunc("GET /api/v1/codex/threads/{id}", server.getCodexThread)
	server.mux.HandleFunc("GET /api/v1/codex/config", server.getCodexConfig)
	server.mux.HandleFunc("PUT /api/v1/codex/config", server.saveCodexConfig)
	server.mux.HandleFunc("POST /api/v1/codex/install", server.installCodex)
	server.mux.HandleFunc("POST /api/v1/ollama/use", server.useOllama)
	server.mux.HandleFunc("PUT /api/v1/skills/{name}", server.saveSkill)
	server.mux.HandleFunc("DELETE /api/v1/skills/{name}", server.resetSkill)
	server.mux.HandleFunc("PUT /api/v1/mcp/{id}", server.saveMCP)
	server.mux.HandleFunc("DELETE /api/v1/mcp/{id}", server.deleteMCP)
	server.mux.HandleFunc("POST /api/v1/mcp/{id}/test", server.testMCP)
	server.mux.HandleFunc("POST /api/v1/mcp/presets/{id}/check", server.checkMCPPreset)
	server.mux.HandleFunc("POST /api/v1/mcp/presets/{id}/install", server.installMCPPreset)
	server.mux.HandleFunc("DELETE /api/v1/mcp/presets/{id}/install", server.uninstallMCPPreset)
	// API 拼错时必须返回 JSON 404，不能落到单页应用入口并伪装成 200 成功。
	server.mux.HandleFunc("GET /api/", func(response http.ResponseWriter, request *http.Request) {
		writeError(response, http.StatusNotFound, "API 不存在")
	})
	server.mux.HandleFunc("GET /", server.static)
}
